// Real browser + real authenticated API. Synthetic media; no paid providers or publishing.
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {join} from 'node:path';
import {chromium} from 'playwright';
import {studioApi} from '../lib/studio-api.js';
import {signSession} from '../lib/google-auth.js';
const projects=new Map(),env={SHOPSHORTS_SESSION_SECRET:'test-browser-secret-32-characters-1234',SHOPSHORTS_GOOGLE_ALLOW_SIGNUPS:'1'};
const store={execution:'cloud-worker',get:async id=>structuredClone(projects.get(id)),list:async()=>[...projects.values()],create:async p=>projects.set(p.id,structuredClone(p)),cas:async(p,r)=>{if(projects.get(p.id)?.revision!==r)return false;projects.set(p.id,structuredClone(p));return true},capabilities:async()=>({fortuneEngine:1,mediaProvider:'higgsfield',image:true,video:true,voice:true,workerAt:new Date().toISOString()}),readAsset:async()=>new Response(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a0e0AAAAASUVORK5CYII=','base64'),{headers:{'content-type':'image/png'}})};
const root=join(import.meta.dirname,'../public'),server=createServer(async(req,res)=>{try{let response;if(req.url.startsWith('/api/studio')){const chunks=[];for await(const b of req)chunks.push(b);response=await studioApi(new Request(`http://127.0.0.1:${server.address().port}${req.url}`,{method:req.method,headers:req.headers,...(chunks.length?{body:Buffer.concat(chunks)}:{})}),env,store);}else{const file=req.url==='/fortune'?'fortune.html':req.url.slice(1);if(!['fortune.html','fortune-app.js','fortune.css'].includes(file)){res.writeHead(404).end();return;}response=new Response(await readFile(join(root,file)),{headers:{'content-type':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html'}});}res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));}catch(e){res.writeHead(500).end(e.message)}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{
 browser=await chromium.launch({headless:true});const context=await browser.newContext();const origin=`http://127.0.0.1:${server.address().port}`;
 await context.addCookies([{name:'ss_google',value:await signSession({type:'user',sub:'browser-user',email:'browser@test.example',exp:Date.now()+600000},env),url:origin}]);
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/fortune');await page.locator('#connection').filter({hasText:'연결됨'}).waitFor();await page.locator('button[type=submit]').click();await page.locator('#episode').waitFor();const first=[...projects.keys()][0];
 await page.locator('#credits').fill('20');await page.locator('#approved').check();await page.locator('#generate').click();await page.waitForFunction(()=>document.querySelector('#generate').textContent.includes('생성 중'));
 const p=projects.get(first);p.task.state='done';for(const s of p.scenes)p.assets[s.id]={key:s.id,kind:'image'};p.revision++;projects.set(first,p);await page.locator('#downloadComic').waitFor();assert.equal(await page.locator('#art img').count(),6);
 await page.locator('input[name=age]').fill('15');assert.equal(await page.locator('#episode').isVisible(),false);assert.equal(await page.locator('#art img').count(),0);await page.locator('select[name=life]').selectOption('auto');await page.locator('input[name=name]').fill('민준');await page.locator('select[name=gender]').selectOption({label:'남성'});await page.locator('button[type=submit]').click();await page.locator('#title').filter({hasText:'민준'}).waitFor();const second=[...projects.values()].find(p=>p.id!==first);assert.equal(second.fortune.input.profile.setting,'school');assert.match(second.scenes[1].prompt,/age 15/);assert.equal(await page.locator('#art img').count(),0);
 await page.locator('select[name=source]').selectOption('provided');await page.locator('input[name=summary]').fill('친구의 말을 다시 확인하면 도움이 됩니다.');await page.locator('input[name=tip]').fill('먼저 질문하세요.');await page.locator('button[type=submit]').click();await page.locator('#fortune').filter({hasText:'친구의 말을 다시 확인'}).waitFor();await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);
 const out='/private/tmp/fortune-engine-preview';await mkdir(out,{recursive:true});await page.screenshot({path:join(out,'mobile.png'),fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:join(out,'desktop.png'),fullPage:true});console.log('PASS: browser inputs, API, generated asset display, stale result clearing, age setting, provided fortune, mobile layout; paid calls 0');
}finally{await browser?.close();await new Promise(r=>server.close(r));}
