import test from 'node:test';
import assert from 'node:assert/strict';
import {fortuneProject,fortuneInput,fortuneEdit,fortuneGuard,continueFortune} from '../lib/fortune.js';
import {studioApi} from '../lib/studio-api.js';
import {signSession} from '../lib/google-auth.js';
const input={profile:{name:'서윤',age:29,gender:'여성',hair:'단발',clothes:'셔츠',life:'auto',setting:'auto'},date:'2026-10-04',output:'motion',fortune:{source:'example',theme:'communication'}};
const env={SHOPSHORTS_SESSION_SECRET:'test-only-secret-32-characters-12345',SHOPSHORTS_GOOGLE_ALLOW_SIGNUPS:'1',SHOPSHORTS_TOKEN:'fixture-worker'};
async function setup(){const data=new Map();const store={execution:'cloud-worker',get:async id=>structuredClone(data.get(id)),list:async()=>[...data.values()],create:async p=>{data.set(p.id,structuredClone(p))},cas:async(p,r)=>{if(data.get(p.id)?.revision!==r)return false;data.set(p.id,structuredClone(p));return true},capabilities:async()=>({fortuneEngine:1,mediaProvider:'higgsfield',image:true,video:true,voice:true,workerAt:new Date().toISOString()})};
const call=async(path,body,user='one',extra={})=>{const cookie=await signSession({type:'user',sub:user,email:user+'@test.example',exp:Date.now()+60000},env);return studioApi(new Request('https://test.example/api/studio/'+path,{method:body?'POST':'GET',headers:{cookie:'ss_google='+cookie,'content-type':'application/json',...extra},...(body?{body:JSON.stringify(body)}:{})}),env,store)};return {data,store,call};}
test('identity is owner+all inputs; age contexts and explicit choices remain independent of gender',async()=>{const a=await fortuneProject(input,'a');assert.equal(a.id,(await fortuneProject(input,'a')).id);assert.notEqual(a.id,(await fortuneProject(input,'b')).id);assert.notEqual(a.id,(await fortuneProject({...input,profile:{...input.profile,age:15}},'a')).id);assert.equal(fortuneInput({...input,profile:{...input.profile,age:15}}).profile.setting,'school');assert.equal(fortuneInput({...input,profile:{...input.profile,gender:'남성',life:'store'}}).profile.setting,'store');assert.throws(()=>fortuneInput({...input,date:'2026-02-30'}));assert.throws(()=>fortuneInput({...input,fortune:{...input.fortune,source:'saju'}}));});
test('episode excludes character sheet from final timeline and blocks publishing',async()=>{const p=await fortuneProject(input,'a');for(const s of p.scenes)p.assets[s.id]={key:s.id,kind:'image'};const edit=fortuneEdit(p);assert.equal(edit.clips.length,6);assert.ok(edit.clips.every(c=>c.sceneId!=='fortune-reference'));assert.throws(()=>fortuneGuard(p,'publish',{}));assert.throws(()=>fortuneGuard(p,'media',{}));});
test('API reuses drafts, isolates list and both read paths, checks CAS and cross-origin',async()=>{const {call}=await setup();let r=await call('fortune',input);assert.equal(r.status,201);const p=(await r.json()).project;r=await call('fortune',input);assert.equal((await r.json()).reused,true);assert.equal((await call('fortune/'+p.id,null,'two')).status,404);assert.equal((await call(p.id,null,'two')).status,404);assert.equal((await call(p.id+'/assets/fortune-1',null,'two')).status,404);assert.deepEqual((await (await call('',null,'two')).json()).projects,[]);assert.equal((await call('fortune/'+p.id+'/generate',{revision:99,maxCredits:20,approved:true})).status,409);assert.equal((await call('fortune',input,'one',{origin:'https://evil.example'})).status,403);});
test('generation checks approval, finite cap, worker freshness before queueing',async()=>{const {call,store}=await setup();const p=(await (await call('fortune',input)).json()).project;const path='fortune/'+p.id+'/generate';assert.equal((await call(path,{revision:0,maxCredits:20,approved:false})).status,400);assert.equal((await call(path,{revision:0,maxCredits:0,approved:true})).status,400);store.capabilities=async()=>({fortuneEngine:1,mediaProvider:'higgsfield',image:true,workerAt:'2000-01-01'});assert.equal((await call(path,{revision:0,maxCredits:20,approved:true})).status,503);store.capabilities=async()=>({fortuneEngine:1,mediaProvider:'higgsfield',image:true,workerAt:new Date().toISOString()});const r=await call(path,{revision:0,maxCredits:20,approved:true});assert.equal(r.status,202);assert.equal((await r.json()).project.task.action,'media');});
test('speech is queued before measured final edit; silent output renders directly',async()=>{const {call,data}=await setup();const p=(await (await call('fortune',input)).json()).project;p.approved=true;for(const s of p.scenes)p.assets[s.id]={key:s.id,kind:'image'};data.set(p.id,p);const r=await call('fortune/'+p.id+'/render',{revision:0,voice:'n2fbxG88jqAoaVPUy3IG'});assert.equal(r.status,202);const narrated=(await r.json()).project;assert.equal(narrated.task.action,'narration');assert.equal(narrated.edit.clips.length,6);const {call:second,data:other}=await setup();other.set(p.id,p);const silent=await second('fortune/'+p.id+'/render',{revision:0,voice:'none'});assert.equal(silent.status,202);assert.equal((await silent.json()).project.task.action,'render');});

test('voice completion durably queues measured render without a browser and preserves the spoken ending',async()=>{
 const p=await fortuneProject(input,'a');p.approved=true;p.voicePreference='n2fbxG88jqAoaVPUy3IG';p.task={action:'narration',state:'done'};
 for(const s of p.scenes){p.assets[s.id]={key:s.id,kind:'image'};if(p.fortune.sceneIds.includes(s.id))p.assets['narration-'+s.id]={key:s.id+'.mp3',kind:'audio',purpose:'narration',voice:p.voicePreference,text:s.narration,duration:9};}
 const next=continueFortune(p);assert.equal(next.task.action,'render');assert.equal(next.task.state,'queued');assert.ok(next.edit.clips.every(c=>c.outFrame>=276));assert.equal(next.edit.clips.length,6);assert.equal(continueFortune(next),next);
});

test('old worker cannot claim new fortune job and insufficient voice quota fails before queueing',async()=>{
 const {call,data,store}=await setup();const p=(await (await call('fortune',input)).json()).project;
 let r=await call('fortune/'+p.id+'/generate',{revision:0,maxCredits:20,approved:true});const queued=(await r.json()).project;
 r=await call(p.id+'/claim',{revision:queued.revision},'one',{authorization:'Bearer fixture-worker'});assert.equal(r.status,409);
 r=await call(p.id+'/claim',{revision:queued.revision,fortuneEngine:1},'one',{authorization:'Bearer fixture-worker'});assert.equal(r.status,200);
 p.approved=true;for(const s of p.scenes)p.assets[s.id]={key:s.id,kind:'image'};data.set(p.id,p);store.capabilities=async()=>({voice:true,audioAccount:{state:'ready',remaining:0}});
 r=await call('fortune/'+p.id+'/render',{revision:0,voice:'n2fbxG88jqAoaVPUy3IG'});assert.equal(r.status,400);assert.equal(data.get(p.id).task,null);
});

test('daily episodes reuse the same owned character while a changed outfit or owner gets a fresh identity',async()=>{
 const {call,data,store}=await setup();const p=(await (await call('fortune',input)).json()).project;p.assets['fortune-reference']={key:`studio/${p.id}/reference.png`,kind:'image',type:'image/png'};data.set(p.id,p);let copies=0;
 store.readAsset=async()=>new Response('fixture-image',{headers:{'content-type':'image/png'}});store.writeAsset=async(key)=>{copies++;assert.ok(key.startsWith('studio/'))};
 const next=(await (await call('fortune',{...input,date:'2026-10-05'})).json()).project;assert.notEqual(next.id,p.id);assert.equal(next.fortune.characterFingerprint,p.fortune.characterFingerprint);assert.equal(next.fortune.referenceReused,true);assert.ok(next.assets['fortune-reference'].key.startsWith(`studio/${next.id}/`));assert.equal(copies,1);
 await call('fortune',{...input,profile:{...input.profile,clothes:'후드티'}});await call('fortune',{...input,date:'2026-10-05'},'two');assert.equal(copies,1);
});
