import { clubLevels } from "./v2-club-lessons";
// Design fixtures only. Language examples and pronunciation aids need native review.
// Phrase tuple: Korean meaning, Japanese + aid, Thai + aid, English + aid, Spanish + aid.
export const curriculum = {
  levels: [
    {
      id: 1,
      title: "한마디 시작",
      goal: "인사하고, 원하는 것을 짧게 말해요.",
      help: "한국어 뜻 · 발음 도움 · 한 문장 따라 말하기",
      challenge: "짧은 한마디로 뜻 전하기",
    },
    {
      id: 2,
      title: "짧은 문답",
      goal: "질문을 이해하고, 한 번 더 주고받아요.",
      help: "질문 듣기 · 답 고르기 · 두 차례 대화",
      challenge: "질문하고 답을 이어 듣기",
    },
    {
      id: 3,
      title: "대화 이어가기",
      goal: "취향과 이유를 말하고, 되물어봐요.",
      help: "이유 덧붙이기 · 후속 질문 · 세 차례 대화",
      challenge: "내 생각과 이유를 함께 전하기",
    },
    {
      id: 4,
      title: "자연스럽게 응용",
      goal: "분위기에 맞게 제안하고, 정중하게 거절해요.",
      help: "표현 바꾸기 · 말투 조절 · 예상 밖 답변",
      challenge: "상대와 상황에 맞게 말 바꾸기",
    },
  ],
  categories: ["전체", "사람들과", "여행에서", "일상에서"],
  scenes: [
    {
      id: "smalltalk",
      title: "스몰토크",
      subtitle: "처음 만난 사람과 편하게",
      category: "사람들과",
      icon: "chat",
      color: "mint",
      role: "여행에서 만난 친구",
      topics: [
        "인사와 자기소개",
        "취미·주말 이야기",
        "공통 관심사",
        "자연스럽게 마무리",
      ],
      prompt: "처음 만난 사람과 이야기를 나누고 있어요.",
      phrases: [
        [
          "한국에서 왔어요.",
          "韓国から来ました。",
          "캉코쿠카라 키마시타",
          "มาจากเกาหลีค่ะ",
          "마 짝 까올리 카",
          "I'm from Korea.",
          "아임 프럼 코리아",
          "Soy de Corea.",
          "소이 데 코레아",
        ],
        [
          "쉬는 날에는 무엇을 하세요?",
          "休みの日は何をしていますか？",
          "야스미노 히와 나니오 시테이마스카",
          "วันหยุดชอบทำอะไรคะ",
          "완 윳 촙 탐 아라이 카",
          "What do you do on your days off?",
          "왓 두 유 두 온 유어 데이즈 오프",
          "¿Qué haces en tu tiempo libre?",
          "께 아세스 엔 뚜 띠엠뽀 리브레",
        ],
        [
          "저도 음악을 좋아해요. 어떤 음악을 자주 들으세요?",
          "私も音楽が好きです。どんな音楽をよく聴きますか？",
          "와타시모 온가쿠가 스키데스. 돈나 온가쿠오 요쿠 키키마스카",
          "ชอบดนตรีเหมือนกันค่ะ ปกติฟังเพลงแนวไหนคะ",
          "촙 돈뜨리 므안 깐 카. 뽁까띠 팡 플렝 내우 나이 카",
          "I like music too. What do you usually listen to?",
          "아이 라이크 뮤직 투. 왓 두 유 유주얼리 리슨 투",
          "A mí también me gusta la música. ¿Qué sueles escuchar?",
          "아 미 땀비엔 메 구스따 라 무시까. 께 수엘레스 에스꾸차르",
        ],
        [
          "이야기해서 즐거웠어요. 다음에 또 이야기해요.",
          "お話しできて楽しかったです。またお話ししましょう。",
          "오하나시 데키테 타노시캇타데스. 마타 오하나시 시마쇼오",
          "คุยสนุกมากค่ะ ไว้คุยกันอีกนะคะ",
          "쿠이 싸눅 막 카. 와이 쿠이 깐 익 나 카",
          "It was nice talking to you. Let’s chat again sometime.",
          "잇 워즈 나이스 토킹 투 유. 렛츠 챗 어겐 썸타임",
          "Me ha gustado hablar contigo. ¡Hablamos otro día!",
          "메 아 구스따도 아블라르 꼰띠고. 아블라모스 오뜨로 디아",
        ],
      ],
    },
    {
      id: "club",
      title: "클럽·바",
      subtitle: "음악을 매개로 자연스럽게",
      category: "사람들과",
      icon: "music",
      color: "peach",
      role: "클럽에서 만난 사람",
      topics: clubLevels.map((level) => level.title),
      prompt: "좋아하는 음악이 나오는 클럽에서 옆 사람과 이야기해요.",
      phrases: clubLevels.map((level) => level.rows.split("\n")[0].split("|")),
    },
    {
      id: "cafe",
      title: "카페",
      subtitle: "내 취향대로 주문하기",
      category: "일상에서",
      icon: "cup",
      color: "peach",
      role: "카페 점원",
      topics: ["주문하기", "추천 묻기", "취향 설명", "주문 바꾸기"],
      prompt: "점원이 주문을 기다리고 있어요. 원하는 음료를 말해 보세요.",
      phrases: [
        [
          "덜 달게 해 주세요.",
          "甘さ控えめでお願いします。",
          "아마사 히카에메데 오네가이시마스",
          "ขอหวานน้อยค่ะ",
          "커 완 너이 카",
          "Less sweet, please.",
          "레스 스위트 플리즈",
          "Menos dulce, por favor.",
          "메노스 둘세 뽀르 파보르",
        ],
        [
          "어떤 음료를 추천하세요?",
          "おすすめの飲み物は何ですか？",
          "오스스메노 노미모노와 난데스카",
          "แนะนำเครื่องดื่มอะไรคะ",
          "내남 크르앙듬 아라이 카",
          "What drink would you recommend?",
          "왓 드링크 우드 유 레커멘드",
          "¿Qué bebida me recomiendas?",
          "께 베비다 메 레꼬미엔다스",
        ],
        [
          "단 음료는 좋아하지 않아서, 설탕 없이 부탁드려요.",
          "甘い飲み物が苦手なので、砂糖なしでお願いします。",
          "아마이 노미모노가 니가테나노데, 사토오 나시데 오네가이시마스",
          "ไม่ชอบเครื่องดื่มหวานค่ะ ขอไม่ใส่น้ำตาลนะคะ",
          "마이 촙 크르앙듬 완 카. 커 마이 싸이 남딴 나 카",
          "I don’t like sweet drinks. No sugar, please.",
          "아이 돈트 라이크 스위트 드링크스. 노 슈거 플리즈",
          "No me gustan las bebidas dulces. Sin azúcar, por favor.",
          "노 메 구스딴 라스 베비다스 둘세스. 씬 아수까르 뽀르 파보르",
        ],
        [
          "죄송하지만, 가능하면 따뜻한 것으로 바꿔 주실 수 있나요?",
          "すみません、できれば温かいものに変えていただけますか？",
          "스미마셍, 데키레바 아타타카이 모노니 카에테 이타다케마스카",
          "ขอโทษค่ะ ถ้าได้ ขอเปลี่ยนเป็นแบบร้อนได้ไหมคะ",
          "커 톳 카. 타 다이 커 쁠리안 뻰 뱁 론 다이 마이 카",
          "Sorry, could I change that to a hot drink if possible?",
          "쏘리, 쿠드 아이 체인지 댓 투 어 핫 드링크 이프 파서블",
          "Disculpa, ¿sería posible cambiarla por una bebida caliente?",
          "디스꿀빠, 세리아 뽀시블레 깜비아를라 뽀르 우나 베비다 깔리엔떼",
        ],
      ],
    },
    {
      id: "restaurant",
      title: "식당",
      subtitle: "맛있는 한 끼를 편하게",
      category: "여행에서",
      icon: "meal",
      color: "mint",
      role: "식당 직원",
      topics: ["자리 요청", "메뉴 질문", "취향·요청", "문제 설명"],
      prompt: "식당 직원에게 필요한 것을 말해 보세요.",
      phrases: [
        [
          "두 명이에요.",
          "二人です。",
          "후타리데스",
          "สองคนค่ะ",
          "썽 콘 카",
          "A table for two, please.",
          "어 테이블 포 투 플리즈",
          "Una mesa para dos, por favor.",
          "우나 메사 빠라 도스 뽀르 파보르",
        ],
        [
          "이 요리는 매운가요?",
          "この料理は辛いですか？",
          "코노 료오리와 카라이데스카",
          "อาหารจานนี้เผ็ดไหมคะ",
          "아한 짠 니 펫 마이 카",
          "Is this dish spicy?",
          "이즈 디스 디시 스파이시",
          "¿Este plato es picante?",
          "에스떼 쁠라또 에스 삐깐떼",
        ],
        [
          "매운 것은 잘 못 먹어요. 덜 맵게 해 주실 수 있나요?",
          "辛いものが苦手です。辛さを控えめにできますか？",
          "카라이 모노가 니가테데스. 카라사오 히카에메니 데키마스카",
          "กินเผ็ดไม่เก่งค่ะ ทำเผ็ดน้อยได้ไหมคะ",
          "낀 펫 마이 껭 카. 탐 펫 너이 다이 마이 카",
          "I can’t eat very spicy food. Could you make it less spicy?",
          "아이 캔트 잇 베리 스파이시 푸드. 쿠드 유 메이크 잇 레스 스파이시",
          "No puedo comer muy picante. ¿Podrían hacerlo menos picante?",
          "노 뿌에도 꼬메르 무이 삐깐떼. 뽀드리안 아세를로 메노스 삐깐떼",
        ],
        [
          "죄송하지만, 주문한 것과 다른 요리가 나온 것 같아요.",
          "すみません、注文したものと違う料理が来たようです。",
          "스미마셍, 추우몬시타 모노토 치가우 료오리가 키타 요오데스",
          "ขอโทษค่ะ ดูเหมือนอาหารจะไม่ตรงกับที่สั่งค่ะ",
          "커 톳 카. 두 므안 아한 짜 마이 뜨롱 깝 티 쌍 카",
          "Excuse me, I think this isn’t what I ordered.",
          "익스큐즈 미, 아이 띵크 디스 이즌트 왓 아이 오더드",
          "Disculpe, creo que esto no es lo que pedí.",
          "디스꿀뻬, 끄레오 께 에스또 노 에스 로 께 뻬디",
        ],
      ],
    },
    {
      id: "hotel",
      title: "호텔",
      subtitle: "체크인부터 부탁까지",
      category: "여행에서",
      icon: "bed",
      color: "blue",
      role: "호텔 직원",
      topics: ["체크인", "시간 확인", "짐 보관", "불편한 점 요청"],
      prompt: "호텔 프런트에서 직원에게 이야기해 보세요.",
      phrases: [
        [
          "체크인하고 싶어요.",
          "チェックインをお願いします。",
          "쳇쿠인오 오네가이시마스",
          "ขอเช็กอินค่ะ",
          "커 첵인 카",
          "I’d like to check in.",
          "아이드 라이크 투 체크 인",
          "Quisiera hacer el check-in.",
          "끼시에라 아세르 엘 체크인",
        ],
        [
          "체크아웃은 몇 시인가요?",
          "チェックアウトは何時ですか？",
          "쳇쿠아우토와 난지데스카",
          "เช็กเอาต์กี่โมงคะ",
          "첵아웃 끼 몽 카",
          "What time is check-out?",
          "왓 타임 이즈 체크아웃",
          "¿A qué hora es la salida?",
          "아 께 오라 에스 라 살리다",
        ],
        [
          "방에 들어갈 수 있을 때까지 짐을 맡길 수 있나요?",
          "部屋に入れるまで荷物を預けられますか？",
          "헤야니 하이레루마데 니모츠오 아즈케라레마스카",
          "ฝากกระเป๋าไว้จนกว่าจะเข้าห้องได้ไหมคะ",
          "팍 끄라빠오 와이 쫀 꽈 짜 카오 헝 다이 마이 카",
          "Can I leave my bags here until my room is ready?",
          "캔 아이 리브 마이 백스 히어 언틸 마이 룸 이즈 레디",
          "¿Puedo dejar las maletas aquí hasta que esté lista la habitación?",
          "뿌에도 데하르 라스 말레따스 아끼 아스따 께 에스떼 리스따 라 아비따시온",
        ],
        [
          "방이 조금 시끄러운데, 가능하면 다른 방으로 바꿔 주실 수 있나요?",
          "部屋が少しうるさいので、できれば別の部屋に変えていただけますか？",
          "헤야가 스코시 우루사이노데, 데키레바 베츠노 헤야니 카에테 이타다케마스카",
          "ห้องค่อนข้างเสียงดังค่ะ ถ้าได้ ขอเปลี่ยนห้องได้ไหมคะ",
          "헝 컨 캉 씨앙 당 카. 타 다이 커 쁠리안 헝 다이 마이 카",
          "My room is a little noisy. Could I move to another room if possible?",
          "마이 룸 이즈 어 리틀 노이지. 쿠드 아이 무브 투 어나더 룸 이프 파서블",
          "Hay un poco de ruido en mi habitación. ¿Sería posible cambiarme a otra?",
          "아이 운 뽀꼬 데 루이도 엔 미 아비따시온. 세리아 뽀시블레 깜비아르메 아 오뜨라",
        ],
      ],
    },
    {
      id: "directions",
      title: "길 찾기·교통",
      subtitle: "낯선 동네에서도 자신 있게",
      category: "여행에서",
      icon: "pin",
      color: "blue",
      role: "길을 알려 주는 사람",
      topics: ["위치 묻기", "방향 확인", "가는 방법", "잘못 들었을 때"],
      prompt: "낯선 동네에서 목적지로 가는 방법을 물어봐요.",
      phrases: [
        [
          "역은 어디에 있나요?",
          "駅はどこですか？",
          "에키와 도코데스카",
          "สถานีอยู่ที่ไหนคะ",
          "싸타니 유 티 나이 카",
          "Where is the station?",
          "웨어 이즈 더 스테이션",
          "¿Dónde está la estación?",
          "돈데 에스따 라 에스따시온",
        ],
        [
          "여기서 걸어서 갈 수 있나요?",
          "ここから歩いて行けますか？",
          "코코카라 아루이테 이케마스카",
          "จากที่นี่เดินไปได้ไหมคะ",
          "짝 티 니 든 빠이 다이 마이 카",
          "Can I walk there from here?",
          "캔 아이 워크 데어 프럼 히어",
          "¿Puedo ir andando desde aquí?",
          "뿌에도 이르 안단도 데스데 아끼",
        ],
        [
          "처음 와서 잘 몰라요. 어떻게 가면 되나요?",
          "初めて来たので、よく分かりません。どう行けばいいですか？",
          "하지메테 키타노데, 요쿠 와카리마셍. 도오 이케바 이이데스카",
          "มาครั้งแรกเลยไม่ค่อยรู้ทางค่ะ ต้องไปยังไงคะ",
          "마 크랑 랙 러이 마이 커이 루 탕 카. 떵 빠이 양 응아이 카",
          "It’s my first time here. How do I get there?",
          "잇츠 마이 퍼스트 타임 히어. 하우 두 아이 겟 데어",
          "Es la primera vez que vengo. ¿Cómo puedo llegar?",
          "에스 라 쁘리메라 베스 께 벵고. 꼬모 뿌에도 예가르",
        ],
        [
          "오른쪽으로 돈 다음에 직진하면 된다는 말씀이죠?",
          "右に曲がってから、まっすぐ行けばいいということですね？",
          "미기니 마갓테카라, 맛스구 이케바 이이토 이우 코토데스네",
          "หมายถึงเลี้ยวขวาแล้วตรงไปใช่ไหมคะ",
          "마이 틍 리아우 콰 래우 뜨롱 빠이 차이 마이 카",
          "So I turn right and then go straight, is that right?",
          "쏘 아이 턴 라이트 앤 덴 고 스트레이트, 이즈 댓 라이트",
          "Entonces, giro a la derecha y luego sigo recto, ¿verdad?",
          "엔똔세스, 히로 아 라 데레차 이 루에고 시고 렉또, 베르닷",
        ],
      ],
    },
    {
      id: "shopping",
      title: "쇼핑",
      subtitle: "고르고, 비교하고, 부탁하기",
      category: "여행에서",
      icon: "bag",
      color: "peach",
      role: "가게 직원",
      topics: ["가격 묻기", "다른 색·크기", "비교하기", "교환 문의"],
      prompt: "가게에서 마음에 드는 물건을 찾았어요.",
      phrases: [
        [
          "얼마인가요?",
          "いくらですか？",
          "이쿠라데스카",
          "ราคาเท่าไหร่คะ",
          "라카 타오 라이 카",
          "How much is it?",
          "하우 머치 이즈 잇",
          "¿Cuánto cuesta?",
          "꾸안또 꾸에스따",
        ],
        [
          "다른 색도 있나요?",
          "ほかの色もありますか？",
          "호카노 이로모 아리마스카",
          "มีสีอื่นไหมคะ",
          "미 씨 은 마이 카",
          "Does it come in other colors?",
          "더즈 잇 컴 인 아더 컬러즈",
          "¿Lo tienen en otros colores?",
          "로 띠에넨 엔 오뜨로스 꼴로레스",
        ],
        [
          "이 디자인이 좋은데, 조금 더 작은 사이즈가 있나요?",
          "このデザインが好きですが、もう少し小さいサイズはありますか？",
          "코노 데자인가 스키데스가, 모오 스코시 치이사이 사이즈와 아리마스카",
          "ชอบแบบนี้ค่ะ มีไซซ์เล็กกว่านี้หน่อยไหมคะ",
          "촙 뱁 니 카. 미 싸이 렉 꽈 니 너이 마이 카",
          "I like this design. Do you have it in a smaller size?",
          "아이 라이크 디스 디자인. 두 유 해브 잇 인 어 스몰러 사이즈",
          "Me gusta este diseño. ¿Lo tienen en una talla más pequeña?",
          "메 구스따 에스떼 디세뇨. 로 띠에넨 엔 우나 따야 마스 뻬께냐",
        ],
        [
          "사이즈가 맞지 않으면 교환할 수 있는지 미리 알고 싶어요.",
          "サイズが合わなかった場合、交換できるか先に知りたいです。",
          "사이즈가 아와나캇타 바아이, 코오칸 데키루카 사키니 시리타이데스",
          "อยากทราบก่อนค่ะ ถ้าไซซ์ไม่พอดี เปลี่ยนได้ไหมคะ",
          "약 쌉 껀 카. 타 싸이 마이 퍼 디 쁠리안 다이 마이 카",
          "Before I buy it, can I exchange it if it doesn’t fit?",
          "비포 아이 바이 잇, 캔 아이 익스체인지 잇 이프 잇 더즌트 핏",
          "Antes de comprarlo, quisiera saber si puedo cambiarlo si no me queda bien.",
          "안떼스 데 꼼쁘라를로, 끼시에라 사베르 시 뿌에도 깜비아를로 시 노 메 께다 비엔",
        ],
      ],
    },
    {
      id: "friends",
      title: "친구와 약속",
      subtitle: "친해진 다음의 대화",
      category: "사람들과",
      icon: "heart",
      color: "mint",
      role: "함께 여행하는 친구",
      topics: ["취향 나누기", "약속 잡기", "대안 제안", "일정 조율"],
      prompt: "친구와 다음에 만날 약속을 정해 봐요.",
      phrases: [
        [
          "또 만나요!",
          "また会いましょう！",
          "마타 아이마쇼오",
          "ไว้เจอกันอีกนะคะ",
          "와이 쩌 깐 익 나 카",
          "See you again soon!",
          "씨 유 어겐 순",
          "¡Hasta pronto!",
          "아스따 쁘론또",
        ],
        [
          "내일 시간 있어요?",
          "明日、時間はありますか？",
          "아시타, 지칸와 아리마스카",
          "พรุ่งนี้ว่างไหมคะ",
          "프룽 니 왕 마이 카",
          "Are you free tomorrow?",
          "아 유 프리 투모로우",
          "¿Tienes tiempo mañana?",
          "띠에네스 띠엠뽀 마냐나",
        ],
        [
          "내일은 바쁜데, 모레 점심은 어때요?",
          "明日は忙しいんですが、明後日のランチはどうですか？",
          "아시타와 이소가시인데스가, 아삿테노 란치와 도오데스카",
          "พรุ่งนี้ไม่ว่างค่ะ มะรืนกินมื้อกลางวันด้วยกันไหมคะ",
          "프룽 니 마이 왕 카. 마 른 낀 므 끌랑 완 두아이 깐 마이 카",
          "I’m busy tomorrow. How about lunch the day after?",
          "아임 비지 투모로우. 하우 어바웃 런치 더 데이 애프터",
          "Mañana no puedo. ¿Qué tal si comemos juntos pasado mañana?",
          "마냐나 노 뿌에도. 께 딸 시 꼬메모스 훈또스 빠사도 마냐나",
        ],
        [
          "조금 늦을 것 같아요. 먼저 들어가 계셔도 괜찮아요.",
          "少し遅れそうです。先に入っていても大丈夫です。",
          "스코시 오쿠레소오데스. 사키니 하잇테이테모 다이조오부데스",
          "น่าจะไปสายหน่อยค่ะ เข้าไปก่อนได้เลยนะคะ",
          "나 짜 빠이 싸이 너이 카. 카오 빠이 껀 다이 러이 나 카",
          "I might be a little late. Feel free to go in first.",
          "아이 마이트 비 어 리틀 레이트. 필 프리 투 고 인 퍼스트",
          "Creo que voy a llegar un poco tarde. Puedes entrar primero.",
          "끄레오 께 보이 아 예가르 운 뽀꼬 따르데. 뿌에데스 엔뜨라르 쁘리메로",
        ],
      ],
    },
  ],
};
