import { sceneLessonPlans } from "./v2-scene-lessons";
// Four app practice stages, not certified proficiency levels.
const definition = {
  levels: [
    {
      id: 1,
      title: "한마디 시작",
      goal: "인사하고, 원하는 것을 짧게 말해요.",
      help: "한국어 뜻 · 발음 도움 · 한 문장 따라 말하기",
      challenge: "짧은 한마디로 뜻 전하기",
    },
    {
      id: 2,
      title: "짧은 문답",
      goal: "질문을 이해하고, 한 번 더 주고받아요.",
      help: "질문 듣기 · 답 고르기 · 두 차례 대화",
      challenge: "질문하고 답을 이어 듣기",
    },
    {
      id: 3,
      title: "대화 이어가기",
      goal: "취향과 이유를 말하고, 되물어봐요.",
      help: "이유 덧붙이기 · 후속 질문 · 세 차례 대화",
      challenge: "내 생각과 이유를 함께 전하기",
    },
    {
      id: 4,
      title: "자연스럽게 응용",
      goal: "분위기에 맞게 제안하고, 정중하게 거절해요.",
      help: "표현 바꾸기 · 말투 조절 · 예상 밖 답변",
      challenge: "상대와 상황에 맞게 말 바꾸기",
    },
  ],
  categories: ["전체", "사람들과", "여행에서", "일상에서"],
  scenes: [
    {
      id: "smalltalk",
      title: "스몰토크",
      subtitle: "처음 만난 사람과 편하게",
      category: "사람들과",
      icon: "chat",
      color: "mint",
      role: "여행에서 만난 친구",
      prompt: "처음 만난 사람과 이야기를 나누고 있어요.",
    },
    {
      id: "club",
      title: "클럽·바",
      subtitle: "음악을 매개로 자연스럽게",
      category: "사람들과",
      icon: "music",
      color: "peach",
      role: "클럽에서 만난 사람",
      prompt: "좋아하는 음악이 나오는 클럽에서 옆 사람과 이야기해요.",
    },
    {
      id: "cafe",
      title: "카페",
      subtitle: "내 취향대로 주문하기",
      category: "일상에서",
      icon: "cup",
      color: "peach",
      role: "카페 점원",
      prompt: "점원이 주문을 기다리고 있어요. 원하는 음료를 말해 보세요.",
    },
    {
      id: "restaurant",
      title: "식당",
      subtitle: "맛있는 한 끼를 편하게",
      category: "여행에서",
      icon: "meal",
      color: "mint",
      role: "식당 직원",
      prompt: "식당 직원에게 필요한 것을 말해 보세요.",
    },
    {
      id: "hotel",
      title: "호텔",
      subtitle: "체크인부터 부탁까지",
      category: "여행에서",
      icon: "bed",
      color: "blue",
      role: "호텔 직원",
      prompt: "호텔 프런트에서 직원에게 이야기해 보세요.",
    },
    {
      id: "directions",
      title: "길 찾기·교통",
      subtitle: "낯선 동네에서도 자신 있게",
      category: "여행에서",
      icon: "pin",
      color: "blue",
      role: "길을 알려 주는 사람",
      prompt: "낯선 동네에서 목적지로 가는 방법을 물어봐요.",
    },
    {
      id: "shopping",
      title: "쇼핑",
      subtitle: "고르고, 비교하고, 부탁하기",
      category: "여행에서",
      icon: "bag",
      color: "peach",
      role: "가게 직원",
      prompt: "가게에서 마음에 드는 물건을 찾았어요.",
    },
    {
      id: "friends",
      title: "친구와 약속",
      subtitle: "친해진 다음의 대화",
      category: "사람들과",
      icon: "heart",
      color: "mint",
      role: "함께 여행하는 친구",
      prompt: "친구와 다음에 만날 약속을 정해 봐요.",
    },
  ],
};
export const curriculum = {
  ...definition,
  scenes: definition.scenes.map((scene) => {
    const plans = sceneLessonPlans[scene.id];
    return {
      ...scene,
      topics: plans.map((plan) => plan.title),
      phrases: plans.map((plan) => plan.rows.split("\n")[0].split("|")),
    };
  }),
};
